name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    #OS
    runs-on: ubuntu-latest

    #Node version used
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    #For using Node.js
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    #For caching the dependencies, so the pipeline doesn't take 
    #too long. Only when a  new dependency is added, all the 
    #packages are installed once again.
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

      
